const CONFIG = {
    introTitle: 'Bé mớ ơii :3',
    introDesc: ` có biết cái này làm gì hongg,
    btnIntro: 'hong biết thì click vào đây nèe :3',
    title: 'Phải chăng em đã yêu ngay từ cái nhìn đầu tiên 😙',
    desc: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'Chọn cái này là k yeu thong :(',
    btnNo: 'chọn cái này là thích thong :3',
    question:'Hiện cái này là biet chọn k yêu thong r :(',
    btnReply: 'Say something to thong <3',
    reply: 'chọn khong yêu nma yêu thì yêu khong yêu thì yêu 🥰 ',
    mess: 'Thong biết mà 🥰. Yêu mớ nhiều nhiều 😘😘',
    messDesc: 'Tối nay 9h qua đón mớ nhaa.',
    btnAccept: 'Okiiiii lun <3',
}
